[project]
name = "talk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "demoji>=1.1.0",
    "funasr>=1.2.7",
    "numpy>=2.3.5",
    "sounddevice>=0.5.3",
    "torch>=2.9.1",
    "torchaudio>=2.9.1",
]
